### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by saioia-msu** [Devolutions/PAM-Providers#13]
What license are these scripts released under?

**Comment by maurice-cote** [comment]
ah right, I will ensure we upload the license.txt ASAP

**Comment by maurice-cote** [comment]
Added both APACHE and MIT license files to repo

**Comment by sevmonster** [comment]
@maurice-cote Looks like you forgot to [update the copyright notice in the Apache license](https://github.com/Devolutions/PAM-Providers/blob/16c7e8b9fa9a4849703fe0915e07bee14d66f0d1/LICENSE-APACHE.txt#L190), and should probably mention in the description that the repository is dual-licensed under both MIT and Apache to avoid confusion.

Thank you for taking a look at this.

**Comment by saioia-msu** [comment]
@maurice-cote Looks like you forgot to [update the copyright notice in the Apache license](https://github.com/Devolutions/PAM-Providers/blob/16c7e8b9fa9a4849703fe0915e07bee14d66f0d1/LICENSE-APACHE.txt#L190), and should probably mention in the README that the repository is dual-licensed under both MIT and Apache to avoid confusion.

Thank you for taking a look at this.

**Comment by maurice-cote** [comment]
all done! I hope this meets community best practices.
